import { FormEvent, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, FileCheck2 } from "lucide-react";
import type { ClosingReceipt, ReasonCode } from "../../data/cloudClosingRepository";
import { describeDifference } from "../../domain/alerts";
import "./closingResult.css";

const REASONS:[ReasonCode,string][]=[["waste_unreported","Avaria ou descarte não lançado"],["courtesy_unreported","Cortesia não lançada"],["count_error","Possível erro de contagem"],["system_error","Possível erro no sistema"],["store_transfer","Transferência entre lojas"],["internal_consumption","Consumo interno"],["other","Outro motivo"]];
export function ClosingResult({receipt,onJustify,onNew}:{receipt:ClosingReceipt;onJustify:(reasonCode:ReasonCode,explanation:string)=>Promise<ClosingReceipt>;onNew:()=>void}){
 const [current,setCurrent]=useState(receipt);const[reason,setReason]=useState<ReasonCode|"">("");const[explanation,setExplanation]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const message=useMemo(()=>describeDifference(current.difference,current.alertLevel),[current]);const needs=current.submissionState==="awaiting_justification";
 async function submit(e:FormEvent){e.preventDefault();if(!reason)return;const min=current.alertLevel==="relevant"||current.alertLevel==="critical"?30:3;if(explanation.trim().length<min){setError(min===30?"Explique com pelo menos 30 caracteres.":"Escreva uma breve justificativa.");return}setBusy(true);setError("");try{setCurrent(await onJustify(reason,explanation.trim()))}catch{setError("Não foi possível enviar a justificativa. Tente novamente.")}finally{setBusy(false)}}
 const submitted=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(current.submittedAt));
 const differenceValue=Math.abs(current.difference).toLocaleString("pt-BR",{maximumFractionDigits:2});const differenceTone=current.difference>0?"surplus":current.difference<0?"shortage":"balanced";
 return <main className={`closing-result-shell ${message.tone}`}><section className="closing-result-card"><div className="result-icon">{current.alertLevel==="correct"?<CheckCircle2/>:<AlertTriangle/>}</div><span className="result-eyebrow">Resultado do fechamento</span><h1>{message.headline}</h1><div className={"result-alert-panel " + differenceTone}><span className="result-difference-label">Diferença apurada</span><strong className="result-difference-value">{differenceValue}</strong><span className="result-difference-unit">equivalentes de pão</span><p className="result-message">{message.text}</p></div><div className="receipt-strip"><span><FileCheck2/><small>Protocolo</small><strong>{current.protocol}</strong></span><span><Clock3/><small>Enviado em</small><strong>{submitted}</strong></span></div>
 {needs?<form className="justification-form" onSubmit={submit}><h2>Conte o que aconteceu</h2><p>A contagem já está bloqueada. A justificativa será anexada sem alterar nenhum número.</p><label>Motivo<select aria-label="Motivo da diferença" value={reason} onChange={e=>setReason(e.target.value as ReasonCode)} required><option value="">Selecione</option>{REASONS.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Justificativa<textarea aria-label="Justificativa" value={explanation} onChange={e=>setExplanation(e.target.value)} placeholder="Explique de forma simples e verdadeira o que pode ter ocorrido." required/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy} type="submit">{busy?"Enviando…":"Enviar justificativa e concluir"}</button></form>:<div className="result-complete"><CheckCircle2/><strong>Fechamento concluído e protegido</strong><span>Os números não podem mais ser alterados pela loja.</span><button type="button" onClick={onNew}>Voltar ao início</button></div>}</section></main>;
}
